branches:
  only:
    - master
language: java
os: linux
jdk: openjdk18

script: true

jobs:
  include:
    - arch: amd64
    - arch: arm64
    - arch: arm64-graviton2
      group: edge
      virt: vm
