branches:
  only:
    - master
language: java
os: linux
jdk: openjdk18
git:
  quiet: true

jobs:
  include:
    - arch: amd64
    - arch: arm64
    - arch: arm64-graviton2
      group: edge
      virt: vm

before_install:
    - git clone https://github.com/UnterrainerInformatik/Travis-Scripts.git travis
    - source travis/functions.Java.sh
    - tr_setProjectSubdir Java
    - source $TRAVIS/before_install.sh
install:
    - source $TRAVIS/install.sh
before_script:
    - source $TRAVIS/before_script.sh
script:
    - source $TRAVIS/script.sh
    - source $TRAVIS/before_deploy.sh